
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compilador.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 40;
  public static final int ASIGNAR = 21;
  public static final int POR = 19;
  public static final int DEVOLVER = 14;
  public static final int SI = 10;
  public static final int DIFERENTE = 23;
  public static final int CORCHETE_DER = 36;
  public static final int CONSTANTE = 7;
  public static final int LLAVE_IZQ = 33;
  public static final int NOT = 30;
  public static final int MENORIGUAL = 26;
  public static final int AND = 28;
  public static final int CARACTER_LIT = 43;
  public static final int IGUAL = 22;
  public static final int SINO = 11;
  public static final int OR = 29;
  public static final int MIENTRAS = 12;
  public static final int ESCRIBIR = 15;
  public static final int PAREN_DER = 32;
  public static final int DIV = 20;
  public static final int ID = 42;
  public static final int PUNTO_COMA = 38;
  public static final int MAYORIGUAL = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int CADENA = 41;
  public static final int MENOS = 18;
  public static final int MENOR = 24;
  public static final int ENTERO_TIPO = 2;
  public static final int BOOLEANO_TIPO = 4;
  public static final int MAYOR = 25;
  public static final int PUNTO = 37;
  public static final int LLAVE_DER = 34;
  public static final int CORCHETE_IZQ = 35;
  public static final int FALSO = 9;
  public static final int LEER = 16;
  public static final int VACIO_TIPO = 6;
  public static final int PARA = 13;
  public static final int VERDADERO = 8;
  public static final int CADENA_TIPO = 3;
  public static final int PAREN_IZQ = 31;
  public static final int CARACTER_TIPO = 5;
  public static final int MAS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO_TIPO",
  "CADENA_TIPO",
  "BOOLEANO_TIPO",
  "CARACTER_TIPO",
  "VACIO_TIPO",
  "CONSTANTE",
  "VERDADERO",
  "FALSO",
  "SI",
  "SINO",
  "MIENTRAS",
  "PARA",
  "DEVOLVER",
  "ESCRIBIR",
  "LEER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIGNAR",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "AND",
  "OR",
  "NOT",
  "PAREN_IZQ",
  "PAREN_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "PUNTO",
  "PUNTO_COMA",
  "COMA",
  "NUMERO",
  "CADENA",
  "ID",
  "CARACTER_LIT"
  };
}

